//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop_Management_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-I0JJGJ1\\MSSQLSERVER2022;Initial Catalog=\"C:\\USERS\\ACER\\SOURCE" +
            "\\REPOS\\PET SHOP MANAGEMENT SYSTEM\\PET SHOP MANAGEMENT SYSTEM\\DBPETSHOP.MDF\";Inte" +
            "grated Security=True;Encrypt=False")]
        public string C__USERS_ACER_SOURCE_REPOS_PET_SHOP_MANAGEMENT_SYSTEM_PET_SHOP_MANAGEMENT_SYSTEM_DBPETSHOP_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_ACER_SOURCE_REPOS_PET_SHOP_MANAGEMENT_SYSTEM_PET_SHOP_MANAGEMENT_SYSTEM_" +
                    "DBPETSHOP_MDFConnectionString"]));
            }
        }
    }
}
